
# Site settings
title: Dy's Home
email: 1556528051@qq.com
description: > # this means to ignore newlines until "baseurl:"
    Keep on coding!
baseurl: "/dy0607.github.io/" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

# User setting
owner: Dy
email: 1556528051@qq.com
facebook_username:
twitter_username:
github_username: dy0607
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: dy0607

# API settings
google_api_key:

# Build settings
gems: [jekyll-paginate]

markdown: kramdown
# toc_levels: 1..2

